import type { Metadata } from "next";

import { SidebarLg } from "@/components/dashboard/sidebar-lg/sidebar-lg-component";
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="relative min-w-full min-h-full p-2 select-none">
      <div className="flex w-5/6 max-w-7xl mx-auto h-full gap-6">
        <nav className="hidden lg:flex lg:w-72 ">
          <SidebarLg />
        </nav>
        <Separator orientation="vertical" className="hidden lg:block" />
        <div className="w-full">{children}</div>
      </div>
    </section>
  );
}
