import type { Metadata } from "next";

import { SidebarLg } from "@/components/dashboard/sidebar-lg/sidebar-lg-component";
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-w-full lg:p-2 select-none flex justify-center">
      <div className="flex lg:w-5/6 max-w-7xl h-full justify-center ">
        <nav className="hidden lg:flex lg:w-72 pr-6">
          <SidebarLg />
        </nav>
        <Separator orientation="vertical" className="hidden lg:block" />
        <div className="w-full px-2 lg:pl-12 lg:pr-0">{children}</div>
      </div>
    </div>
  );
}
